name: Veracode SCA

on:
  workflow_dispatch:

jobs:
  veracode-sca:
    runs-on: self-hosted
    steps:
      # Repo Checkout
      - uses: actions/checkout@v4.1.1
        with:
          repository: ${{ github.event.client_payload.repository.full_name }}
          ref: ${{ github.event.client_payload.sha }}

      - run: |
          ls -la
